### ISSUE TITLE
TypeError: getRouter is not a function

### ISSUE THREAD

**Issue by raju-a** [probot/example-google-cloud-function#16]
`module.exports = (app, { getRouter }) => {
  const router = getRouter("/sync-testing");
  router.use(require("express").static("public"));
  // Add a new route
  router.get("/hello-world", (req, res) => {
    res.send("Hello World");
  });`

When I start the app with `probot run ./app.js,` I get this
`TypeError: getRouter is not a function`

Please help me on this

**Comment by gr2m** [comment]
can you share the full logs? What version of probot are you using? You need to be using v11

**Comment by raju-a** [comment]
Thank you for your response
Here I have add 3 files which I created in google cloud function
https://gist.github.com/raju-a/aec6ad7887b9c9f9418831b5833ad575

<img width="1408" alt="Screenshot 2021-04-09 at 9 25 19 AM" src="https://user-images.githubusercontent.com/11290721/114126216-a49c4600-9915-11eb-8e10-4b9c49dd851e.png">

**Comment by gr2m** [comment]
Sorry, I get now what the problem is. 

`getRouter` is not set when you use it with anything other than `probot run ./app.js`. When you run the function on GCF, then GCF is taking care of routing, there is no long-living node process running in the background that is also acting as router.

In a future release of probot we will probably remove the `getRouter` function altogether, to prevent that confusion.
